### ISSUE TITLE
Takes longer than normal to run

### ISSUE THREAD

**Issue by eddiemoore** [EasyAsABC123/grunt-standard#1]
This seems to take a lot longer than it should to run.
When I was running it as an npm script with `npm test` it only took a couple of seconds. The grunt plugin is taking almost 20 seconds to complete.

**Comment by ArmorDarks** [comment]
Did you make any measurements with `time-grunt`? Maybe it's taking more time during loading. In such case, `jit-grunt` might help.

**Comment by EasyAsABC123** [comment]
@eddiemoore let me know if this is still the case...there are minor optimizations that could probably be squeaked out

**Comment by EasyAsABC123** [comment]
only item left to do is a reporter, closing thanks
