### ISSUE TITLE
Use new `--fix`

### ISSUE THREAD

**Issue by ArmorDarks** [EasyAsABC123/grunt-standard#11]
Hello

Thanks for Grunt plugin.

Standard 8.0.0 and higher uses new flag `--fix` instead of `standard-format`. Thus, we can drop one dependency.

Details: https://github.com/feross/standard/blob/master/CHANGELOG.md#800---2016-08-23

**Comment by ArmorDarks** [comment]
@pdehaan ping?

**Comment by pdehaan** [comment]
@ArmorDarks Hey, I don't use **standard** or this module anymore. Would you have any interest in transferring the repo and npm module to you?

**Comment by ArmorDarks** [comment]
Hi!

Thanks for offer, but we no longer using this module too (we replaced it with non-Grunt based standard), and in generally plans to move completely from Grunt in future.

I think it worth to add in readme and description mention like "MAINTAINER WANTED".

**Comment by pdehaan** [comment]
I believe this was addressed by #12 (but we'll still need to publish a new version to npm)
