### ISSUE TITLE
Globals from package.json not being considered

### ISSUE THREAD

**Issue by rafaelpivato** [EasyAsABC123/grunt-standard#3]
According [standard](https://github.com/feross/standard#i-use-a-library-that-pollutes-the-global-namespace-how-do-i-prevent-variable-is-not-defined-errors) project, `package.json` configuration options should be honored, like globals definition. Nevertheless, globals passed through a `package.json` file will be ignored by _grunt-standard_.

If you have this excerpt in your `package.json`, _standard_ will run fine by command line, taking defined globals in consideration, while _grunt-standard_ will ignore and bypass the configuration:

```
"standard": {
    "global": ["angular"]
}
```

**Comment by rafaelpivato** [comment]
Looks like this is related to #4 

Updating the requirement should help.

**Comment by Tvrqvoise** [comment]
This one too appears to be resolved by #5.

**Comment by nicolindemann** [comment]
In my setting ("grunt": "^0.4.5", "grunt-standard": "^1.0.2") the globals are still not considered. 

Can someone confirm this issue is resolved?

**Comment by Tvrqvoise** [comment]
@pdehaan , can you publish a new version on NPM?

**Comment by pdehaan** [comment]
Published to npm as [v2.0.0](https://www.npmjs.com/package/grunt-standard).
I actually don't use this package very much anymore. If anybody wants GitHub/npm access and wants to maintain it (or just rewrite from scratch and publish from their npm/GibHub account) let me know and we can sort it out. xoxo.

**Comment by Tvrqvoise** [comment]
I'd be happy to help maintain the project.

**Comment by pdehaan** [comment]
@Tvrqvoise Added you as a collaborator in GitHub, send me your npm username and I can try to figure out how to give you npm publish access too.
