### ISSUE TITLE
Use ranges for dependencies

### ISSUE THREAD

**Issue by Tvrqvoise** [EasyAsABC123/grunt-standard#7]
All the dependencies are locked currently.  I'm personally of the opinion that we should use fairly permissive (^5.0.0, etc) ranges, otherwise we'll have to update the component every time there's a fix upstream of us.  We always have the shinkwrap stuff if we want to roll back to a specific version of the deps (and, my understanding is that the consuming project should do the shrinkwrap, not the component).

Thoughts?

**Comment by pdehaan** [comment]
Done. Published to npm as [v2.0.0](https://www.npmjs.com/package/grunt-standard).
